version: "3"

services:
  ollama:
    image: ollama/ollama:0.3.11
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    tty: true
    networks:
      - ollama_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    restart: always
    networks:
      - ollama_network

volumes:
  ollama:
  open-webui:

networks:
  ollama_network:
    driver: bridge
